
spring:
  application:
    name: Api-Gateway-Service
  cloud:
    gateway:
      routes:
        - id: TRANSFER-SERVICE
          uri: lb://TRANSFER-SERVICE
          predicates:
            - Path=/api/rt/v1/transfer/**
          filters:
            - RewritePath=/api/rt/v1/(?<segment>.*), /$\{segment}

        - id: BANKSTATEMENT-SERVICE
          uri: lb://BANKSTATEMENT-SERVICE
          predicates:
            - Path=/api/rt/v1/bankstatement/**
          filters:
            - RewritePath=/api/rt/v1/(?<segment>.*), /$\{segment}

        - id: CRUD-SERVICE
          uri: lb://CRUD-SERVICE
          predicates:
            - Path=/api/rt/v1/**
          filters:
            - RewritePath=/api/rt/v1/(?<segment>.*), /$\{segment}

        - id: TRANSFERCHECK-SERVICE
          uri: lb://TRANSFERCHECK-SERVICE
          predicates:
            - Path=/api/rt/v1/transfer/check/**
          filters:
            - RewritePath=/api/rt/v1/(?<segment>.*), /$\{segment}



server:
  port: 8080
  ssl:
    enabled: true
    key-alias: firmkey
    key-store: firmkeystore.pkcs12
    key-store-password: 123456
    key-password: 123456

eureka:
  instance:
    hostname: localhost
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: ${server.port}
    home-page-url: https://${eureka.instance.hostname}:${server.port}/
    status-page-url: https://${eureka.instance.hostname}:${server.port}/info
    health-check-url: https://${eureka.instance.hostname}:${server.port}/health
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:6901/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always # actuator에서 디테일한 정보들을 확인하기 위해 설정
