
spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: TRANSFER-SERVICE
          uri: lb://TRANSFER-SERVICE
          predicates:
            - Path=/transfer/**
        - id: BANKSTATEMENT-SERVICE
          uri: lb://BANKSTATEMENT-SERVICE
          predicates:
            - Path=/bankstatement/**
        - id: CRUD-SERVICE
          uri: lb://CRUD-SERVICE
          predicates:
            - Path=/crud-service/**
          filters:
            - RewritePath=/crud-service/(?<segment>.*), /$\{segment}
        - id: TEST-SERVICE-1
          predicates:
            - Path=/first-service/**
          uri: lb://TEST-SERVICE-1
          filters:
            - RewritePath=/first-service/(?<segment>.*), /$\{segment}

server:
  port: 8080
  ssl:
    enabled: true
    key-alias: firmkey
    key-store: firmkeystore-test.pkcs12
    key-store-password: 123456
    key-password: 123456
    trust-store: firmkeytrust.ts
    trust-store-password: 123456

eureka:
  instance:
    hostname: localhost
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: ${server.port}
    home-page-url: https://${eureka.instance.hostname}:${server.port}/
    status-page-url: https://${eureka.instance.hostname}:${server.port}/info
    health-check-url: https://${eureka.instance.hostname}:${server.port}/health
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:6901/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always # actuator에서 디테일한 정보들을 확인하기 위해 설정
