
spring:
  application:
    name: test-service-2

server:
  port: 8082

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${server.port}}
  client:
    service-url:
      defaultZone: http://localhost:6901/eureka/